using YamlDotNet.Core;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace RayTagger.Core.Configuration;

/// <summary>
/// Reads and writes <see cref="EnergyCalibrationProfile"/> to a standalone YAML file (default
/// path: <c>./energy-calibration.yaml</c> next to <c>tagger.yaml</c>). Keeping calibration out of
/// the main config lets us own the file 100% — write a clean, machine-formatted YAML without
/// fighting to preserve hand-written comments in <c>tagger.yaml</c>.
/// </summary>
public static class EnergyCalibrationProfileLoader
{
    private static readonly IDeserializer Deserializer = new DeserializerBuilder()
        .WithNamingConvention(UnderscoredNamingConvention.Instance)
        .Build();

    private static readonly ISerializer Serializer = new SerializerBuilder()
        .WithNamingConvention(UnderscoredNamingConvention.Instance)
        .ConfigureDefaultValuesHandling(DefaultValuesHandling.OmitDefaults)
        .Build();

    /// <summary>
    /// Header written at the top of the file. Conveys provenance + the "tool-owned" nature so
    /// users don't expect their edits to survive a re-calibrate.
    /// </summary>
    private const string FileHeader =
        "# RayTagger — energy calibration profile.\n" +
        "# Auto-generated by `tagger calibrate-energy` / the UI Calibrate Energy button.\n" +
        "# Tool-owned: any hand edits will be overwritten on the next calibration run.\n" +
        "# To reset to defaults, delete this file (or clear analysis.energy.calibration_file in tagger.yaml).\n" +
        "\n";

    public static EnergyCalibrationProfile Load(string path)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(path);

        if (!File.Exists(path))
        {
            throw new ConfigurationException($"Calibration profile not found: {path}");
        }

        var yaml = File.ReadAllText(path);
        try
        {
            return Deserializer.Deserialize<EnergyCalibrationProfile>(yaml)
                ?? throw new ConfigurationException($"Calibration profile is empty: {path}");
        }
        catch (YamlException ex)
        {
            throw new ConfigurationException(
                $"YAML deserialization failed for {path} (line {ex.Start.Line}, column {ex.Start.Column}): {ex.Message}",
                ex);
        }
    }

    /// <summary>
    /// Writes the profile atomically: serialize to <c>path.tmp</c>, then File.Move to
    /// <paramref name="path"/>. Avoids corrupt half-written files if the process is killed mid-write.
    /// </summary>
    public static void Save(string path, EnergyCalibrationProfile profile)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(path);
        ArgumentNullException.ThrowIfNull(profile);

        var directory = Path.GetDirectoryName(Path.GetFullPath(path));
        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        var body = Serializer.Serialize(profile);
        var tempPath = path + ".tmp";
        File.WriteAllText(tempPath, FileHeader + body);
        File.Move(tempPath, path, overwrite: true);
    }
}
